### ISSUE TITLE
请问哪里有体现BM25检索，如何用命名实体模型去生成关键词

### ISSUE THREAD

**Issue by SetonLiang** [TebooNok/HiQA#10]
1. `result_list = reset_by_lucene(question, results, threshold=0.5, lucene_weight=0.5)`
2. `returned_values = filter_knowledge(question, result_list)`
您好，请问这两步我可以理解为是基于三个methods的re-ranking和CNED方法吗
如果是的话，哪里有用到BM25搜索呢，且代码中是如何利用命名实体模型去生成关键词的(utils/filter.py.critic_keywords)

**Comment by TebooNok** [comment]
您好，我们使用 [whoosh](https://github.com/mchaput/whoosh)作为全文检索引擎，该引擎支持BM25。我们使用的CNED是gpt-4，输入是所有文档的标题和前200个token。 具体来说，

1. ```reset_by_lucene()```中，输入的results是向量相似度排序的结果，我们将其创建为whoosh索引，再用用户query去检索一遍并加权，得到经过向量+字符检索的chunks。
2. 这个项目里没放调用gp-4的代码和提示词，该模型建议用户根据场景选取，CNED的输出是一组list，类似于critic_keywords()
3. 最后，在```utils/filter.py.filter_knowledge()```方法中，输入为第一步输出的results，我们先match问题中出现的keywords，再用keywords去重组该results，将出现keywords的chunks向前移（越多越好，实际上是使用多头链表的想法），得到最终的输出。

**Comment by SetonLiang** [comment]
那在CNED中prompt主要聚焦在如产品名字这样的实体吗? 前200个token是指什么呢

**Comment by TebooNok** [comment]
对，聚焦于准确的“产品/型号”，short and clear，最好再写几个fewshot。
前200个token是指用PyPDF2之类的编辑器打开文档，读取第一页的最开头部分的文字。有时候文档的**文件名**命名不规范，文档的首页标题会更准。参考这篇德州仪器的[变频器使用手册](https://www.ti.com.cn/cn/lit/ds/symlink/lm231.pdf?ts=1732091867134&ref_url=https%253A%252F%252Fwww.ti.com.cn%252Fzh-cn%252Famplifier-circuit%252Fspecial-function%252Ffrequency-converters%252Fproducts.html) （LMx31x Precision Voltage-to-Frequency Converters）
这个CNED小程序需要根据具体的文档特色去定制，比如有的需要去掉首页。

**Comment by SetonLiang** [comment]
好的，感谢！
