### ISSUE TITLE
又有个小问题

### ISSUE THREAD

**Issue by SHIMURA0** [TebooNok/HiQA#2]
现在运行app_streamlit.py这个文件没有问题啦，可以生成网页，但是在query栏输入信息时，会出现这个bug
NotFoundError: Error code: 404 - {'error': {'message': 'Invalid URL (POST /v1/completions/embeddings)', 'type': 'invalid_request_error', 'param': None, 'code': None}} 我怀疑这个是不是和询问的格式有关，不太清楚应该提问回这怎么修复这个bug，谢谢

**Comment by TebooNok** [comment]
query需要调用openai的embedding接口，这里可能是openai版本不对，或者api的供应商不对。 请尝试修改.env里配置的openai url和key，本地安装最新的openai python package，先测试是否能正常调用embedding

**Comment by SHIMURA0** [comment]
好的我自己已解决，多谢了
