### ISSUE TITLE
Is this project configurable to use Langchain or Llamaindex framework? And, would open source LLM perform similarly?

### ISSUE THREAD

**Issue by GxTeo** [TebooNok/HiQA#3]

**Comment by TebooNok** [comment]
Hi, In the file ``` /utils/openai_proxy.py``` , specifically within the ``` send_message(question, knowledge) ``` function, I've implemented a straightforward method to call OpenAI's API. It can be replaced with alternative APIs such as llamaindex/langchain/custom llm.

As discussed in the relevant literature, GPT-4 demonstrates significant advancements over previous models. However, upon recent evaluation, I've also considered newer models like qwen-1.5-72b. It's worth noting that these models are rapidly improving and showing promising results.
