### ISSUE TITLE
请问代码中哪里体现的MRR部分的呢

### ISSUE THREAD

**Issue by liuxinbin12138** [TebooNok/HiQA#4]
您好，我在代码中没有发现MRR部分，想请教一下论文中的超参是如何设置的，以及关键词命中个数您是用什么技术统计并排序的呢？

**Comment by TebooNok** [comment]
您好，
1. /service
/knowledge_client.py - reset_by_lucene()
2. /utils/filter - filter_knowledge()

上面两个函数，前者是利用搜索引擎方法对知识段的分数加权，后者用预先设置的关键词对知识段进行重排。
