### ISSUE TITLE
关于pdf2md

### ISSUE THREAD

**Issue by SWHL** [TebooNok/HiQA#5]
很棒的工作，感谢开源。我有两个问题，想请教一下：
1. Markdown Formatter这部分的工作，PDF文档是中文论文文档吗？还是说是英文的文档数据呢？
2. 合成的pdf和md对的数据集有计划开源吗？

感谢！

**Comment by TebooNok** [comment]
您好，
1. MF是一个通用的PDF to Markdown的小工具，可以运行在任意PDF文件上，得到其markdown的格式。 主要适用于很长且结构良好的文档/手册。
2. 我们数据集的pdf和对应的markdown文件，都在datasets目录下。
