### ISSUE TITLE
关于build_tool/section2embedding.py文件下的函数参数里的max_token问题

### ISSUE THREAD

**Issue by handsomexiu** [TebooNok/HiQA#7]
作者您好，我有一个问题
这里的build_tool/section2embedding.py里面的
def split_and_embed(section, encoding,max_tokens=8000):
    # Get the title from the first line
    lines = section.split("\n")
    title = lines[0]
    content = "\n".join(lines[1:])
到
def section_to_embed(file_name: str):
    max_tokens = 800
……
        if n_tokens < max_tokens:
                        new_df_entries.append({'section': section, 'n_tokens': n_tokens, 'embedding': get_embedding(section, engine=embedding_model)})
                    else:
                        for new_section in split_and_embed(section, encoding):
                            new_df_entries.append({'section': new_section, 'n_tokens': len(encoding.encode(new_section)), 'embedding': get_embedding(new_section, engine=embedding_model)})
真的没有问题吗，在else这里没有修改max_tokens的值，且在split_and_embed中的maxtoken还是8000，而且也没有二次检测，我没有实验，但感觉有点问题，麻烦了

**Comment by TebooNok** [comment]
您好，感谢提问。
我觉得这里有问题，
```
def section_to_embed(file_name: str):
max_tokens = 800
```
这里max_tokens应该设置为8000，
这是由于[openai embedding](https://platform.openai.com/docs/guides/embeddings/embedding-models)模型的最大输入长度为8191，而section的划分是按章节划分，长度可能超过embedding模型的最大值。如果某个section超过了，则拆分为多个section，拆分得到的sections共享元信息。

其中，split_and_embed使用递归+二分的方法去拆目前的section，直到满足条件（len<max_tokens）
所以max_tokens是一个常数，应该不用修改。

**Comment by handsomexiu** [comment]
原来如此，openai的embedding处理的上下文这么长



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Xinyue Chen ***@***.***&gt;
发送时间: 2024年6月18日 22:20
收件人: TebooNok/HiQA ***@***.***&gt;
抄送: Yi Ningyuan ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [TebooNok/HiQA] 关于build_tool/section2embedding.py文件下的函数参数里的max_token问题 (Issue #7)

**Comment by TebooNok** [comment]
感谢指正 😄
