### ISSUE TITLE
Image feedback of query sample

### ISSUE THREAD

**Issue by vizrium** [TebooNok/HiQA#8]
Thanks for the excellent work. I'm trying to get some image feedback but it seems not working as described in the paper. This is the UI and inputs I have attempted. Might there be something I have missed to make it work?

<img width="759" alt="截屏2024-07-01 01 03 24" src="https://github.com/TebooNok/HiQA/assets/28765800/b810dcf1-3069-43ea-aa6d-e7d31e1e0542">

**Comment by TebooNok** [comment]
Hi, I just move the datasets from the main project to [MasQA](https://github.com/TebooNok/MasQA). It is required to download that dataset and put it to ```/datasets/``` folder. So, we need to confirm datasets exists in your local project.
